spring.application.name=SalesAnalytics 

# --- Configuração do Banco de Dados (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/sales_db
spring.datasource.username=postgres
spring.datasource.password=3010

# --- Configuração do Hibernate ---
spring.jpa.hibernate.ddl-auto=update
pring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true